version: "3.8"

services:
  nginx-webserver: 
    image: nginx:latest
    container_name: nginx
    restart: always

  mongo-database:
   image: mongo:latest
   container_name: mongodb
   restart: always
   ports:
     - "27020:27017/tcp"
   environment:
     MONGO_INITDB_ROOT_USERNAME: nodesimpleapps
     MONGO_INITDB_ROOT_PASSWORD: nodesimpleapps6969!
     MONGO_INITDB_DATABASE: admin

  reverse-proxy:
    image: nginx:latest
    container_name: reverse-proxy
    volumes:
      - ./nginx/default.conf:/etc/nginx/nginx.conf
      - ./nginx/load-balancer.conf:/etc/nginx/sites-enabled/localhost.conf
    ports:
      - 80:80
      - 443:443
    depends_on:
      - nginx-webserver

  nodetestdocker-apps:
    image: haradakumiko/nodetestdocker:latest
    container_name: nodetestdocker
    ports:
      - "8082:3000/tcp"
    environment:
      - MONGO_HOST=mongo-database
      - MONGO_PORT=27017
      - MONGO_USER=nodesimpleapps
      - MONGO_PASSWORD=nodesimpleapps6969!
      - MONGO_DATABASE=animeapps
      - API_URL=/api
    depends_on:
      - mongo-database